<a href="https://colab.research.google.com/github/Megala30/Python-Workspace/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv")

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
np.__version__

'2.0.2'

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.shape

(891, 12)

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.shape[1]

12

In [ ]:
df.shape[0]

891

In [ ]:
df.size

10692

In [ ]:
df.columns.tolist()

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
subset = df[['Name', 'Age']]
subset

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [ ]:
#loc is a label based naming
print("Row 1: ")
print(df.loc[1])

Row 1:
PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

In [ ]:
df.loc[0:10, ['Name', 'Age']]

                                                 Name   Age
0                             Braund, Mr. Owen Harris  22.0
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
5                                    Moran, Mr. James   NaN
6                             McCarthy, Mr. Timothy J  54.0
7                      Palsson, Master. Gosta Leonard   2.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0

In [ ]:
print(df.iloc[-1, -1])

Q

In [ ]:
df.iloc[::2, :3].head()

<bound method NDFrame.head of      PassengerId  Survived  Pclass
0              1         0       3
2              3         1       3
4              5         0       3
6              7         0       1
8              9         1       3
..           ...       ...     ...
882          883         0       3
884          885         0       3
886          887         0       2
888          889         0       3
890          891         0       3

[446 rows x 3 columns]>

In [8]:
import pandas as pd
df = pd.read_csv('/Titanic-Dataset.csv')

In [11]:
female_survivors = df[(df['Sex'] == 'female') & (df['Survived'] == 1)]

female_survivors

In [15]:
mf = pd.read_csv('/Iris.csv')

In [21]:
mf.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [22]:
mf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [25]:
species_count = mf['Species'].value_counts()
display(species_count )

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [27]:
mf.shape

(150, 6)

In [28]:
df.dtypes
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [35]:
mf.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [37]:
colmn_list = mf[['SepalLengthCm', 'PetalLengthCm', 'Species']]
colmn_list

     SepalLengthCm  PetalLengthCm         Species
0              5.1            1.4     Iris-setosa
1              4.9            1.4     Iris-setosa
2              4.7            1.3     Iris-setosa
3              4.6            1.5     Iris-setosa
4              5.0            1.4     Iris-setosa
..             ...            ...             ...
145            6.7            5.2  Iris-virginica
146            6.3            5.0  Iris-virginica
147            6.5            5.2  Iris-virginica
148            6.2            5.4  Iris-virginica
149            5.9            5.1  Iris-virginica

[150 rows x 3 columns]

In [38]:
df.info(50)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [41]:
print(df.iloc[75 :101])

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
75    76            6.6           3.0            4.4           1.4
76    77            6.8           2.8            4.8           1.4
77    78            6.7           3.0            5.0           1.7
78    79            6.0           2.9            4.5           1.5
79    80            5.7           2.6            3.5           1.0
80    81            5.5           2.4            3.8           1.1
81    82            5.5           2.4            3.7           1.0
82    83            5.8           2.7            3.9           1.2
83    84            6.0           2.7            5.1           1.6
84    85            5.4           3.0            4.5           1.5
85    86            6.0           3.4            4.5           1.6
86    87            6.7           3.1            4.7           1.5
87    88            6.3           2.3            4.4           1.3
88    89            5.6           3.0            4.1           1.3
89    90            5.5           2.5            4.0           1.3
90    91            5.5           2.6            4.4           1.2
91    92            6.1           3.0            4.6           1.4
92    93            5.8           2.6            4.0           1.2
93    94            5.0           2.3            3.3           1.0
94    95            5.6           2.7            4.2           1.3
95    96            5.7           3.0            4.2           1.2
96    97            5.7           2.9            4.2           1.3
97    98            6.2           2.9            4.3           1.3
98    99            5.1           2.5            3.0           1.1
99   100            5.7           2.8            4.1           1.3
100  101            6.3           3.3            6.0           2.5

             Species
75   Iris-versicolor
76   Iris-versicolor
77   Iris-versicolor
78   Iris-versicolor
79   Iris-versicolor
80   Iris-versicolor
81   Iris-versicolor
82   Iris-versicolor
83   Iris-versicolor
84   Iris-versicolor
85   Iris-versicolor
86   Iris-versicolor
87   Iris-versicolor
88   Iris-versicolor
89   Iris-versicolor
90   Iris-versicolor
91   Iris-versicolor
92   Iris-versicolor
93   Iris-versicolor
94   Iris-versicolor
95   Iris-versicolor
96   Iris-versicolor
97   Iris-versicolor
98   Iris-versicolor
99   Iris-versicolor
100   Iris-virginica

In [47]:
flowers_count = mf['Species'].value_counts()
setosa_count = flowers_count['Iris-setosa']
print(f"Number of Setosa flowers: {setosa_count}")

Number of Setosa flowers: 50

In [48]:
colmn_list = mf[['PetalLengthCm']]
print(colmn_list > 5)

     PetalLengthCm
0            False
1            False
2            False
3            False
4            False
..             ...
145           True
146          False
147           True
148           True
149           True

[150 rows x 1 columns]